Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/Music_Product_Order__c.object-meta.xml
<CustomObject>
    <label>Music Product Order</label>
    <nameField>
        <displayFormat>ORD-{000000}</displayFormat>
        <label>Music Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Music Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/fields/Order_Late_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Late_Date__c</fullName>
    <description>A minimum of seven days after the order start date.</description>
    <label>Order Late Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Music_Product_Order__c/fields/Order_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Start_Date__c</fullName>
    <description>The date the order was placed</description>
    <label>Order Start Date</label>
    <type>Date</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/classes/TestOrderDetail.cls
@isTest
public class TestOrderDetail {
	
    @isTest static void TestOrderList(){
 		
		Music_Product_Order__c prodOrder = new Music_Product_Order__c();
        prodOrder.Order_Late_Date__c = Date.newInstance(2016, 9, 1);
        prodOrder.Order_Start_Date__c = Date.newInstance(2016, 8, 18);
        insert prodOrder;
        
        Test.startTest();	
        
        GetOrderList.getOrderList();             
        Test.StopTest();

    }
}