Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/Music_Product_Order__c.object-meta.xml
<CustomObject>
    <label>Music Product Order</label>
    <nameField>
        <displayFormat>ORD-{000000}</displayFormat>
        <label>Music Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Music Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product_Order__c/fields/Customer_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_s_Last_Name__c</fullName>
    <description>Customer&apos;s last name.</description>
    <label>Customer&apos;s Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Music_Store_Accounts__c/Music_Store_Accounts__c.object-meta.xml
<CustomObject>
    <description>Custom Accounts object</description>
    <label>Music Store Account</label>
    <nameField>
        <label>Music Store Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Store Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Store_Accounts__c/fields/Account_Opened_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Opened_Date__c</fullName>
    <label>Account Opened Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/popularController.cls
//couldn't figure out how to change controller name; it's the controller for the accounts details summary page
public with sharing class popularController {

    public List<Music_Store_Accounts__c> accountsList {get; set;}
    public List<Music_Product_Order__c> ordersList {get; set;}
    
    //controller method that stores the info about the accounts and orders to lists with a limit of 3 
    public popularController() {
		this.accountsList = [SELECT Name,Account_Opened_Date__c FROM Music_Store_Accounts__c LIMIT 3];
        this.ordersList = [SELECT Customer_s_Last_Name__c, Name FROM Music_Product_Order__c LIMIT 3];
    }
    //returns the account info to the vf page
    public List<Music_Store_Accounts__c> getTempAccounts(){
        return this.accountsList;
    }
    //returns the account info to the vf page
    public List<Music_Product_Order__c> getTempOrders(){
        return this.ordersList;
    }
    //logic for button to open the accounts details vf page
    public pageReference accountsPage(){
        pageReference pg = new pageReference('/apex/AccountDetails');
        pg.setRedirect(true);
        return pg;
    }
    //logic for button to open the orders details vf page
    public pageReference ordersPage(){
        pageReference pg = new pageReference('/apex/OrderDetails');
        pg.setRedirect(true);
        return pg;
    }
}