force-app/main/default/objects/Music_Product__c/Music_Product__c.object-meta.xml
<CustomObject>
    <label>Music Product</label>
    <nameField>
        <label>Music Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product__c/fields/Estimated_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Quantity__c</fullName>
    <label>Estimated Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Music_Product__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Music_Product__c/fields/Instrument_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Sub_Type__c</fullName>
    <label>Instrument Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brass</fullName>
            </value>
            <value>
                <fullName>Percussion</fullName>
            </value>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Woodwind</fullName>
            </value>
            <value>
                <fullName>Keyboard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FilterTable.cls
public class FilterTable {
    string type;
    list<Music_Product__c> filter;
    public string gettype()
    {
        return this.type;
    }
    public void settype(string type)
    {
        this.type = type;
        system.debug(type);
    }
    public list<SelectOption>  getOpt()
    {
        list<SelectOption> opt=new List<SelectOption>{
        new SelectOption('Woodwind','Woodwind'),
        new SelectOption('Brass','Brass'),
        new SelectOption('Keyboard','Keyboard'),
		new SelectOption('Percussion','Percussion'),
        new SelectOption('String','String')
        };
        return opt;
    }
	public void setFilter()
    {
        list<Music_Product__c> records=[SELECT name, image__c, price__c, estimated_quantity__c, instrument_sub_type__c 
                                        FROM Music_Product__c WHERE Instrument_Sub_Type__c=:type]; 

        this.filter=records;
    }
  		public list<music_product__c> getFilter()
        {
            return filter;
        }
}