force-app/main/default/objects/Music_Product__c/Music_Product__c.object-meta.xml
<CustomObject>
    <label>Music Product</label>
    <nameField>
        <label>Music Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/Music_Product_Order__c.object-meta.xml
<CustomObject>
    <label>Music Product Order</label>
    <nameField>
        <displayFormat>ORD-{000000}</displayFormat>
        <label>Music Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Music Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product_Order__c/fields/Customer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_First_Name__c</fullName>
    <description>Customer&apos;s first name</description>
    <label>Customer First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Music_Product_Order__c/fields/Customer_s_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_s_Last_Name__c</fullName>
    <description>Customer&apos;s last name.</description>
    <label>Customer&apos;s Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Music_Product_Order__c/fields/Number_of_Music_Products_1_ordered__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Music_Products_1_ordered__c</fullName>
    <label>Number of Music Products 1 ordered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Music_Product_Order__c/fields/Number_of_Music_Products_2_ordered__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Music_Products_2_ordered__c</fullName>
    <label>Number of Music Products 2 ordered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Music_Product_Order__c/fields/Number_of_Music_Products_3_ordered__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Music_Products_3_ordered__c</fullName>
    <label>Number of Music Products 3 ordered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/orderInstrumentDetailsController.cls
//controller for the main order detail page
public with sharing class orderInstrumentDetailsController {
    
    public List<Music_Product_Order__c> ordersList {get; set;}
    public List<Music_Product__c> productList {get; set;}
    
    //controller method that stores the info about the orders to a list with a limit of 10 
    public orderInstrumentDetailsController() {
		this.ordersList = [SELECT Name, Customer_First_Name__c, Customer_s_Last_Name__c, Number_of_Music_Products_1_ordered__c,Number_of_Music_Products_2_ordered__c,Number_of_Music_Products_3_ordered__c FROM Music_Product_Order__c LIMIT 10];
    }

    //returns the account info to the vf page
    public List<Music_Product_Order__c> getTempOrders(){
        return this.ordersList;
    }
    
    public pageReference previousPage(){
        pageReference pg = new pageReference('/apex/AccountsOrdersDetails');
        pg.setRedirect(true);
        return pg;
    }
    
}