force-app/main/default/objects/Music_Product__c/Music_Product__c.object-meta.xml
<CustomObject>
    <label>Music Product</label>
    <nameField>
        <label>Music Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revature_Music_Class__c/Revature_Music_Class__c.object-meta.xml
<CustomObject>
    <label>Revature Music Class</label>
    <nameField>
        <label>Revature Music Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revature Music Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revature_Music_Class__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Revature_Music_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class__c/fields/Instruments__c.field-meta.xml
<CustomField>
    <fullName>Instruments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instruments</label>
    <referenceTo>Music_Product__c</referenceTo>
    <relationshipLabel>Revature Music Classes</relationshipLabel>
    <relationshipName>Revature_Music_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advanced</fullName>
            </value>
            <value>
                <fullName>Beginners</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Revature_Music_Class__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4 weeks sessions</fullName>
            </value>
            <value>
                <fullName>6 weeks sessions</fullName>
            </value>
            <value>
                <fullName>8 weeks sessions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Revature_Music_Class__c/fields/Students_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Students_Enrolled__c</fullName>
    <label>Students Enrolled</label>
    <summaryForeignKey>Student__c.Classes__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/notificationControllerTest.cls
@isTest
public class notificationControllerTest {
@isTest static void testgetAllStartingClasses(){
    
      Revature_Music_Class__c c = new Revature_Music_Class__c(Name= 'violin lesson', Session__c='4 weeks session',Starting_Date__c = system.today());
      insert c;
       
     Test.StartTest();
     
		List<Revature_Music_Class__c> results =[SELECT Name, Instruments__r.Name,Instructor__r.Name,Session__c,Level__c,Starting_Date__c,Students_Enrolled__c From Revature_Music_Class__c WHERE Starting_Date__c >:system.today() LIMIT 3];
          
 
     Test.StopTest();
  
    
}
}