force-app/main/default/objects/Music_Product__c/Music_Product__c.object-meta.xml
<CustomObject>
    <label>Music Product</label>
    <nameField>
        <label>Music Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product__c/fields/Estimated_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Quantity__c</fullName>
    <label>Estimated Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/Music_Product_Order__c.object-meta.xml
<CustomObject>
    <label>Music Product Order</label>
    <nameField>
        <displayFormat>ORD-{000000}</displayFormat>
        <label>Music Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Music Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product_Order__c/fields/Music_Product_Purchased_1__c.field-meta.xml
<CustomField>
    <fullName>Music_Product_Purchased_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Music Product_Purchased 1</label>
    <referenceTo>Music_Product__c</referenceTo>
    <relationshipLabel>Music Product Orders</relationshipLabel>
    <relationshipName>Music_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/fields/Music_Product_Purchased_2__c.field-meta.xml
<CustomField>
    <fullName>Music_Product_Purchased_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Music Product Purchased 2</label>
    <referenceTo>Music_Product__c</referenceTo>
    <relationshipLabel>Music Product Orders (Music Product Purchased 2)</relationshipLabel>
    <relationshipName>Music_Product_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/fields/Order_Late_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Late_Date__c</fullName>
    <description>A minimum of seven days after the order start date.</description>
    <label>Order Late Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Music_Product_Order__c/fields/Order_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Start_Date__c</fullName>
    <description>The date the order was placed</description>
    <label>Order Start Date</label>
    <type>Date</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/classes/MusicProductItemControllerTest.cls
@isTest
public class MusicProductItemControllerTest {
	static string instrumentName = 'Saxophone';
    static string instrumentDescription = 'This is a test description';
    static integer numberOfOrders = 30;
    static integer totalSupply = 10;
    static Id testID;
    
    @TestSetup
    static void makeData(){
        
        //Creates instruments for use in the database
        Music_Product__c myInstrument = new Music_Product__c();
        myInstrument.name = instrumentName;
        Music_Product__c unusedInstrument = new Music_Product__c();
        unusedInstrument.name = 'Trumpet';
        myInstrument.Estimated_Quantity__c = totalSupply;
        unusedInstrument.Estimated_Quantity__c = 20;
        myInstrument.Description__c = instrumentDescription;

        INSERT myInstrument;
        INSERT unusedInstrument;

        //Creates a list of orders to be used for listing
        List<Music_Product_Order__c> sampleOrders = new List<Music_Product_Order__c>();

        //Creates sample orders with the related instrument
        for(integer i = 0; i < numberOfOrders; i++){
            Music_Product_Order__c newOrder = new Music_Product_Order__c();
            newOrder.Music_Product_Purchased_2__c = myInstrument.id;
            newOrder.Music_Product_Purchased_1__c = unusedInstrument.id;
            newOrder.Order_Start_Date__c = system.today();
            newOrder.Order_Late_Date__c = system.today().addDays(10);
            sampleOrders.add(newOrder);
        }

        INSERT sampleOrders;

    }
    
    @isTest
    public static void testGetTotalOrders(){
        Test.startTest();
        
        string instrumentName = 'Saxophone';
        Music_Product__c testProd = [SELECT id FROM Music_Product__c WHERE name=:instrumentName LIMIT 1];
        integer count = MusicProductItemController.getTotalOrders(testProd);
        
        System.assertEquals(count, 30);
        
        Test.stopTest();
    }
}