force-app/main/default/objects/Music_Product__c/Music_Product__c.object-meta.xml
<CustomObject>
    <label>Music Product</label>
    <nameField>
        <label>Music Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/Music_Product_Order__c.object-meta.xml
<CustomObject>
    <label>Music Product Order</label>
    <nameField>
        <displayFormat>ORD-{000000}</displayFormat>
        <label>Music Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Music Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product_Order__c/fields/Music_Product_Purchased_1__c.field-meta.xml
<CustomField>
    <fullName>Music_Product_Purchased_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Music Product_Purchased 1</label>
    <referenceTo>Music_Product__c</referenceTo>
    <relationshipLabel>Music Product Orders</relationshipLabel>
    <relationshipName>Music_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/fields/Music_Product_Purchased_2__c.field-meta.xml
<CustomField>
    <fullName>Music_Product_Purchased_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Music Product Purchased 2</label>
    <referenceTo>Music_Product__c</referenceTo>
    <relationshipLabel>Music Product Orders (Music Product Purchased 2)</relationshipLabel>
    <relationshipName>Music_Product_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/fields/Music_Product_Purchased_3__c.field-meta.xml
<CustomField>
    <fullName>Music_Product_Purchased_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Music Product Purchased 3</label>
    <referenceTo>Music_Product__c</referenceTo>
    <relationshipLabel>Music Product Orders (Music Product Purchased 3)</relationshipLabel>
    <relationshipName>Music_Product_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/instrumentControllerTest.cls
@isTest
public class instrumentControllerTests{

    string instrumentName = 'Saxophone';
    string instrumentDescription = 'This is a test description';
    integer numberOfOrders = 30;

    @TestSetup
    static void makeData(){
        
        Music_Product__c myInstrument = new Music_Product__c();
        myInstrument.name = instrumentName;
        Music_Product__c unusedInstrument = new Music_Product__c();
        myInstrument.name = 'Trumpet';

        INSERT myInstrument;

        List<Music_Product_Order__c> sampleOrders = new List<Music_Product_Order__c>();

        //Creates sample orders

        for(integer i = 0; i < numberOfOrders; i++){
            Music_Product_Order__c newOrder = new Music_Product_Order__c();
            newOrder.Music_Product_Purchased_2__c = myInstrument;
            newOrder.Music_Product_Purchased_1__c = unusedInstrument;
            sampleOrders.add(newOrder);
        }

        INSERT sampleOrders;

    }

    @isTest
    public static void instrumentController_getName(){

        //Need to figure out how to pass in the instrument id here

        string returnedName = instrumentController.getName();
        system.assertEquals(instrumentName,  returnedName);

    }

    @isTest
    public static void instrumentController_getDescription(){

        //Need to figure out how to pass in the instrument id here
        string retunedDescription = instrumentController.getName();
        system.assertEquals(instrumentDescription,  retunedDescription);

    }

    @isTest
    public static void instrumentController_getNumberOfOrders(){

        integer returnedNumOrders = [SELECT COUNT() FROM Music_Product_Order__c WHERE Music_Product_Purchased_1__c = :instrumentName OR Music_Product_Purchased_2__c = :instrumentName OR Music_Product_Purchased_3__c = :instrumentName];
        assertEquals(numberOfOrders, returnedNumOrders);
    }


}