force-app/main/default/objects/Music_Product__c/Music_Product__c.object-meta.xml
<CustomObject>
    <label>Music Product</label>
    <nameField>
        <label>Music Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product__c/fields/Estimated_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Quantity__c</fullName>
    <label>Estimated Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/Music_Product_Order__c.object-meta.xml
<CustomObject>
    <label>Music Product Order</label>
    <nameField>
        <displayFormat>ORD-{000000}</displayFormat>
        <label>Music Product  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Music Product Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product_Order__c/fields/Music_Product_Purchased_1__c.field-meta.xml
<CustomField>
    <fullName>Music_Product_Purchased_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Music Product_Purchased 1</label>
    <referenceTo>Music_Product__c</referenceTo>
    <relationshipLabel>Music Product Orders</relationshipLabel>
    <relationshipName>Music_Product_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/fields/Music_Product_Purchased_2__c.field-meta.xml
<CustomField>
    <fullName>Music_Product_Purchased_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Music Product Purchased 2</label>
    <referenceTo>Music_Product__c</referenceTo>
    <relationshipLabel>Music Product Orders (Music Product Purchased 2)</relationshipLabel>
    <relationshipName>Music_Product_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product_Order__c/fields/Music_Product_Purchased_3__c.field-meta.xml
<CustomField>
    <fullName>Music_Product_Purchased_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Music Product Purchased 3</label>
    <referenceTo>Music_Product__c</referenceTo>
    <relationshipLabel>Music Product Orders (Music Product Purchased 3)</relationshipLabel>
    <relationshipName>Music_Product_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class__c/Revature_Music_Class__c.object-meta.xml
<CustomObject>
    <label>Revature Music Class</label>
    <nameField>
        <label>Revature Music Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revature Music Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/instrumentController.cls
public with sharing class instrumentController {
    
    //Variable declarations
    public Music_Product__c currentProduct {get; set; }
    public transient Integer totalOrders;
    public List<Revature_Music_Class__c> classes = new List<Revature_Music_Class__c>();
    public integer numberOfOrders;
    public integer totalSupply;

    //Gets the ID of the passed object and finds the instrument of that ID
    public instrumentController() {
        ID instrumentID = ApexPages.CurrentPage().getParameters().get('id');
        this.currentProduct = [SELECT name, description__c, Estimated_Quantity__c FROM Music_Product__c WHERE id=:instrumentID LIMIT 1];
    }

    //Done
    public string getName(){

        return this.currentProduct.name;

    }

    //Description needs to be added by Max
    public string getDescription(){

        return this.currentProduct.description__c;

    }

    //Gets the total number of orders
    //Needs to account for the different fields from order
    public integer getTotalOrders(){

        try{
            totalOrders = [SELECT COUNT() FROM Music_Product_Order__c WHERE Music_Product_Purchased_1__c=:currentProduct.name OR Music_Product_Purchased_2__c=:currentProduct.name OR Music_Product_Purchased_3__c=:currentProduct.name];
        }catch(Exception e){
            system.debug('There was an error in getting the number of orders of the instrument type' + currentProduct.name);
            return null;
        }
        return totalOrders;

    }

    //Gets all of the classes associated with that instrument
    //Needs to have instruments added to classes by Max
    public List<Revature_Music_Class__c> getClasses(){

        this.classes = [SELECT name FROM Revature_Music_Class__c WHERE Revature_Music_Class__c.instruments INCLUDES(:this.currentProduct.name)];
        return classes;

    }

    public decimal getTotalSupply(){

        return this.currentProduct.Estimated_Quantity__c;

    }

}