force-app/main/default/objects/Music_Product__c/Music_Product__c.object-meta.xml
<CustomObject>
    <label>Music Product</label>
    <nameField>
        <label>Music Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product__c/fields/Estimated_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Quantity__c</fullName>
    <label>Estimated Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product__c/fields/Instrument_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Sub_Type__c</fullName>
    <label>Instrument Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Woodwind</fullName>
            </value>
            <value>
                <fullName>Brass</fullName>
            </value>
            <value>
                <fullName>Percussion</fullName>
            </value>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Keyboard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instrument</fullName>
            </value>
            <value>
                <fullName>Music book</fullName>
            </value>
            <value>
                <fullName>Strings</fullName>
            </value>
            <value>
                <fullName>Valve oil</fullName>
            </value>
            <value>
                <fullName>Mouthpieces</fullName>
            </value>
            <value>
                <fullName>Tuner</fullName>
            </value>
            <value>
                <fullName>Measuring devices</fullName>
            </value>
            <value>
                <fullName>Stands</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/classes/SearchInstrumentListController.cls
public class SearchInstrumentListController {
    
    // Acts as a controller for our Aura component, server side 
    
	// @AuraEnabled tells SF that this method will be called from an Aura Component
    // Get the list of music product base on search value 
    // Method must be static to call it from an Aura component
    @AuraEnabled
    public static List<Music_Product__c> fetchInstruments(String searchKeyword) {
        List<Music_Product__c> returnList = new List<Music_Product__c>();
        
        // If search value is null then return all music products. Else search 
        String searchKey = String.isBlank(searchKeyword) ? '%%' : '$' + searchKeyword + '%';
        
        returnList = [SELECT Id,
                             Name,
                             Product_Type__c,
                             Estimated_Quantity__c,
                             Instrument_Sub_Type__c
                      FROM Music_Product__c
                      WHERE Name
                      LIKE :searchKey
                      LIMIT 3];
        
        // return list of products back to Aura component
        return returnList;
    }

}