force-app/main/default/objects/Music_Product__c/Music_Product__c.object-meta.xml
<CustomObject>
    <label>Music Product</label>
    <nameField>
        <label>Music Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Music_Product__c/fields/Estimated_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Quantity__c</fullName>
    <label>Estimated Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/classes/MusicProductFormControllerTest.cls
@isTest
public class MusicProductFormControllerTest {
	
    @isTest
    public static void testSaveItem(){
        Test.startTest();
        
        string instrumentName = 'TestInstrument';
        Music_Product__c myInstrument = new Music_Product__c();
        myInstrument.name = instrumentName;
        myInstrument.Estimated_Quantity__c = 15;
        
        MusicProductFormController.saveItem(myInstrument);
        
        Music_Product__c testProd = [SELECT id, Estimated_Quantity__c FROM Music_Product__c WHERE name=:instrumentName LIMIT 1];
        
        System.assertEquals(testProd.Estimated_Quantity__c, 15);
        
        Test.stopTest();
    }
}