force-app/main/default/objects/Music_Store_Accounts__c/Music_Store_Accounts__c.object-meta.xml
<CustomObject>
    <description>Custom Accounts object</description>
    <label>Music Store Account</label>
    <nameField>
        <label>Music Store Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Store Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revature_Music_Class__c/Revature_Music_Class__c.object-meta.xml
<CustomObject>
    <label>Revature Music Class</label>
    <nameField>
        <label>Revature Music Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revature Music Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revature_Music_Class__c/fields/Assistant_Instructor__c.field-meta.xml
<CustomField>
    <fullName>Assistant_Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assistant Instructor</label>
    <referenceTo>Music_Store_Accounts__c</referenceTo>
    <relationshipLabel>Revature Music Classes</relationshipLabel>
    <relationshipName>Revature_Music_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class__c/fields/Class_address__c.field-meta.xml
<CustomField>
    <fullName>Class_address__c</fullName>
    <label>Class address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Revature_Music_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class__c/fields/Instruments_Offered__c.field-meta.xml
<CustomField>
    <fullName>Instruments_Offered__c</fullName>
    <description>The instrument taught during the class.</description>
    <label>Instruments Offered</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cymbal</fullName>
            </value>
            <value>
                <fullName>Piano</fullName>
            </value>
            <value>
                <fullName>Harmonica</fullName>
            </value>
            <value>
                <fullName>Clairnet</fullName>
            </value>
            <value>
                <fullName>Tambouirne</fullName>
            </value>
            <value>
                <fullName>Saxaphone</fullName>
            </value>
            <value>
                <fullName>Flute</fullName>
            </value>
            <value>
                <fullName>Bass Guitar</fullName>
            </value>
            <value>
                <fullName>Ukelele</fullName>
            </value>
            <value>
                <fullName>Recorder</fullName>
            </value>
            <value>
                <fullName>Violin</fullName>
            </value>
            <value>
                <fullName>Trumpet</fullName>
            </value>
            <value>
                <fullName>Sitar</fullName>
            </value>
            <value>
                <fullName>Guitar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Revature_Music_Class__c/fields/Revature_Music_Class_Roster__c.field-meta.xml
<CustomField>
    <fullName>Revature_Music_Class_Roster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revature Music Class Roster</label>
    <referenceTo>Revature_Music_Class_Roster__c</referenceTo>
    <relationshipLabel>Revature Music Classes</relationshipLabel>
    <relationshipName>Revature_Music_Classes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class__c/fields/Students_currently_in_Class__c.field-meta.xml
<CustomField>
    <fullName>Students_currently_in_Class__c</fullName>
    <description>Number of Students currently in class</description>
    <label>Students currently in Class</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class_Roster__c/Revature_Music_Class_Roster__c.object-meta.xml
<CustomObject>
    <label>Revature Music Class Roster</label>
    <nameField>
        <label>Revature Music Class Roster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revature Music Class Rosters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revature_Music_Class_Roster__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Revature Music Class Rosters</relationshipLabel>
    <relationshipName>Revature_Music_Class_Rosters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class_Roster__c/fields/Revature_Music_Class__c.field-meta.xml
<CustomField>
    <fullName>Revature_Music_Class__c</fullName>
    <label>Revature Music Class</label>
    <referenceTo>Revature_Music_Class__c</referenceTo>
    <relationshipLabel>Revature Music Class Rosters</relationshipLabel>
    <relationshipName>Revature_Music_Class_Rosters</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/rmsClassesController.cls
public with sharing class rmsClassesController {

    //variable declarations
    public Revature_Music_Class__c currentClass {get; set;}
    public User currentInstructor = new User();
    public Music_Store_Accounts__c currentAssistantInstructor = new Music_Store_Accounts__c();
    public Revature_Music_Class_Roster__c currentClassRoster = new Revature_Music_Class_Roster__c();
   
    

    //Gets the ID of the objects passed and finds the Id of the corresponding class
    public rmsClassesController(){
        ID classID = ApexPages.CurrentPage().getParameters().get('id');
        this.currentClass = [SELECT Name, Instructor__c, Revature_Music_Class_Roster__c, Students_currently_in_Class__c, Assistant_Instructor__c, Instruments_Offered__c, Class_address__c FROM Revature_Music_Class__c WHERE id=:classID LIMIT 1];
        
    }

    public string getName(){
        return this.currentClass.Name;
    }

    public string getcurrentInstructor(){
        this.currentInstructor = [SELECT Name, ID FROM User WHERE Id =:this.currentClass.Instructor__c LIMIT 1 ];
        return currentInstructor.Name;
    }

    public Decimal getStudentsInClass(){
        return this.currentClass.Students_currently_in_Class__c;
    } 

    public string getcurrentAssistantInstructor(){
        this.currentAssistantInstructor = [SELECT Name, ID FROM Music_Store_Accounts__c WHERE Id =:this.currentClass.Assistant_Instructor__c LIMIT 1];
        return currentAssistantInstructor.Name;
    }

    public string getcurrentClassRoster(){
        this.currentClassRoster = [SELECT Name, ID FROM Revature_Music_Class_Roster__c WHERE Id =:this.currentClass.Revature_Music_Class_Roster__c LIMIT 1];
        return currentClassRoster.Name;
        
    }

    public string getClassAddress(){
        return this.currentClass.Class_address__c;
    }
}