force-app/main/default/objects/Revature_Music_Class__c/Revature_Music_Class__c.object-meta.xml
<CustomObject>
    <label>Revature Music Class</label>
    <nameField>
        <label>Revature Music Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revature Music Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Revature Meusic Store - P1/force-app/main/default/objects/Revature_Music_Class__c/fields/Revature_Music_Class_Roster__c.field-meta.xml
<CustomField>
    <fullName>Revature_Music_Class_Roster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revature Music Class Roster</label>
    <referenceTo>Revature_Music_Class_Roster__c</referenceTo>
    <relationshipLabel>Revature Music Classes</relationshipLabel>
    <relationshipName>Revature_Music_Classes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class_Roster__c/Revature_Music_Class_Roster__c.object-meta.xml
<CustomObject>
    <label>Revature Music Class Roster</label>
    <nameField>
        <label>Revature Music Class Roster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revature Music Class Rosters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revature_Music_Class_Roster__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Revature Music Class Rosters</relationshipLabel>
    <relationshipName>Revature_Music_Class_Rosters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revature_Music_Class_Roster__c/fields/Revature_Music_Class__c.field-meta.xml
<CustomField>
    <fullName>Revature_Music_Class__c</fullName>
    <label>Revature Music Class</label>
    <referenceTo>Revature_Music_Class__c</referenceTo>
    <relationshipLabel>Revature Music Class Rosters</relationshipLabel>
    <relationshipName>Revature_Music_Class_Rosters</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/rmsClassesControllerTest.cls
@isTest
public class rmsClassesControllerTest {
    
    static string className = 'This is a test class name';
    static string contactName = 'Cena';
    static string rosterName = 'This is a test roster name';


    @TestSetup
    static void makeData(){
        
        //Create new class with a test name
        Revature_Music_Class__c newClass = new Revature_Music_Class__c();
        newClass.name = className;
        INSERT newClass;

        //Create a new contact with a test name
        contact newContact = new contact();
        newContact.LastName = contactName;
        INSERT newContact;

        //Create a new roster with a test name
        Revature_Music_Class_Roster__c newRoster = new Revature_Music_Class_Roster__c();
        newRoster.name = rosterName;
        newRoster.Revature_Music_Class__c = newClass.Id;
        newRoster.contact__c = newContact.Id;
        INSERT newRoster;


    }

}