Revature Meusic Store - P1/force-app/main/default/objects/Account/fields/Percussion_Instruments__c.field-meta.xml
<CustomField>
    <fullName>Percussion_Instruments__c</fullName>
    <label>Percussion Instruments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Piano</fullName>
            </value>
            <value>
                <fullName>Drums</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/String_Instrument__c.field-meta.xml
<CustomField>
    <fullName>String_Instrument__c</fullName>
    <label>String Instrument</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guitar</fullName>
            </value>
            <value>
                <fullName>Violin</fullName>
            </value>
            <value>
                <fullName>Banjo</fullName>
            </value>
            <value>
                <fullName>Harp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Woodwind_Instruments__c.field-meta.xml
<CustomField>
    <fullName>Woodwind_Instruments__c</fullName>
    <label>Woodwind Instruments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flute</fullName>
            </value>
            <value>
                <fullName>Clarinet</fullName>
            </value>
            <value>
                <fullName>Recorder</fullName>
            </value>
            <value>
                <fullName>Didgeridoo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Store_Accounts__c/Music_Store_Accounts__c.object-meta.xml
<CustomObject>
    <description>Custom Accounts object</description>
    <label>Music Store Account</label>
    <nameField>
        <label>Music Store Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Music Store Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Store_Accounts__c/fields/Account_Opened_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Opened_Date__c</fullName>
    <label>Account Opened Date</label>
    <type>Date</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Store_Accounts__c/fields/Brass_Instrument__c.field-meta.xml
<CustomField>
    <fullName>Brass_Instrument__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does the user play brass instruments.</description>
    <label>Brass Instrument</label>
    <type>Checkbox</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Store_Accounts__c/fields/Percussion_Instruments__c.field-meta.xml
<CustomField>
    <fullName>Percussion_Instruments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does the account play any percussion instruments?</description>
    <label>Percussion Instruments</label>
    <type>Checkbox</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Store_Accounts__c/fields/String_Instrument__c.field-meta.xml
<CustomField>
    <fullName>String_Instrument__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does the account play string instruments.</description>
    <label>String Instrument</label>
    <type>Checkbox</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/objects/Music_Store_Accounts__c/fields/Woodwind_Instruments__c.field-meta.xml
<CustomField>
    <fullName>Woodwind_Instruments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does the account play any woodwind instruments?</description>
    <label>Woodwind Instruments</label>
    <type>Checkbox</type>
</CustomField>

Revature Meusic Store - P1/force-app/main/default/classes/accountDetailsController.cls
public class accountDetailsController {
  
    @AuraEnabled
    public static List<Music_Store_Accounts__c> getTempAccounts(){
        if(!schema.SObjectType.Account.isAccessible()){
            throw new AuraHandledException('You cannot access the Music_Store_Account__c object');
        }
        List<Music_Store_Accounts__c> tempAccounts = [SELECT Id, Name,Account_Opened_Date__c, Brass_Instrument__c, Percussion_Instruments__c, String_Instrument__c, Woodwind_Instruments__c FROM Music_Store_Accounts__c LIMIT 10];
        return tempAccounts;
    }
    
}